# Generated by Django 5.1.6 on 2025-05-08 16:41

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='aql_level',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='colors',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, default=list, null=True, size=None),
        ),
        migrations.AddField(
            model_name='section',
            name='default_defects',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, null=True, size=None),
        ),
        migrations.AddField(
            model_name='section',
            name='include_carton_inspected',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='section',
            name='include_carton_offered',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='section',
            name='inspection_level',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='is_garment_section',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='section',
            name='sampling_plan',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='severity',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='sizes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), blank=True, default=list, null=True, size=None),
        ),
    ]
