# Generated by Django 5.1.6 on 2025-03-04 05:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_template'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('conducted_by', models.CharField(blank=True, max_length=255, null=True)),
                ('conducted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('site', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(default='draft', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'inspections',
            },
        ),
        migrations.CreateModel(
            name='InspectionResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'inspection_responses',
            },
        ),
        migrations.CreateModel(
            name='MediaAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='template_media/')),
                ('file_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('document', 'Document')], default='image', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'media_attachments',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('response_type', models.CharField(choices=[('Text', 'Text'), ('Number', 'Number'), ('Checkbox', 'Checkbox'), ('Yes/No', 'Yes/No'), ('Multiple choice', 'Multiple choice'), ('Slider', 'Slider'), ('Media', 'Media'), ('Annotation', 'Annotation'), ('Date & Time', 'Date & Time'), ('Site', 'Site'), ('Inspection date', 'Inspection date'), ('Person', 'Person'), ('Inspection location', 'Inspection location')], default='Text', max_length=50)),
                ('required', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('min_value', models.IntegerField(blank=True, default=0, null=True)),
                ('max_value', models.IntegerField(blank=True, default=100, null=True)),
            ],
            options={
                'db_table': 'questions',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='QuestionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'question_options',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_response', models.TextField(blank=True, null=True)),
                ('number_response', models.FloatField(blank=True, null=True)),
                ('boolean_response', models.BooleanField(blank=True, null=True)),
                ('date_response', models.DateTimeField(blank=True, null=True)),
                ('site_id', models.CharField(blank=True, max_length=255, null=True)),
                ('person_id', models.CharField(blank=True, max_length=255, null=True)),
                ('location_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'responses',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('order', models.PositiveIntegerField()),
                ('is_collapsed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'sections',
                'ordering': ['order'],
            },
        ),
        migrations.RenameField(
            model_name='template',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='template',
            name='last_published',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='template',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='template_logos/'),
        ),
        migrations.AddIndex(
            model_name='template',
            index=models.Index(fields=['created_at'], name='templates_created_2dfe96_idx'),
        ),
        migrations.AddIndex(
            model_name='template',
            index=models.Index(fields=['updated_at'], name='templates_updated_30d236_idx'),
        ),
        migrations.AlterModelTable(
            name='template',
            table='templates',
        ),
        migrations.AddField(
            model_name='inspection',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='users.template'),
        ),
        migrations.AddField(
            model_name='inspectionresponse',
            name='inspection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspection_responses', to='users.inspection'),
        ),
        migrations.AddField(
            model_name='mediaattachment',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_attachments', to='users.question'),
        ),
        migrations.AddField(
            model_name='questionoption',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='users.question'),
        ),
        migrations.AddField(
            model_name='response',
            name='choice_response',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responses', to='users.questionoption'),
        ),
        migrations.AddField(
            model_name='response',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='users.question'),
        ),
        migrations.AddField(
            model_name='inspectionresponse',
            name='response',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspection_responses', to='users.response'),
        ),
        migrations.AddField(
            model_name='section',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='users.template'),
        ),
        migrations.AddField(
            model_name='question',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='users.section'),
        ),
        migrations.AddIndex(
            model_name='inspection',
            index=models.Index(fields=['template'], name='inspections_templat_8b563a_idx'),
        ),
        migrations.AddIndex(
            model_name='inspection',
            index=models.Index(fields=['conducted_at'], name='inspections_conduct_3f51a5_idx'),
        ),
        migrations.AddIndex(
            model_name='inspection',
            index=models.Index(fields=['status'], name='inspections_status_352e25_idx'),
        ),
        migrations.AddIndex(
            model_name='mediaattachment',
            index=models.Index(fields=['question'], name='media_attac_questio_42a70d_idx'),
        ),
        migrations.AddIndex(
            model_name='mediaattachment',
            index=models.Index(fields=['file_type'], name='media_attac_file_ty_33be64_idx'),
        ),
        migrations.AddIndex(
            model_name='questionoption',
            index=models.Index(fields=['question'], name='question_op_questio_dc3834_idx'),
        ),
        migrations.AddIndex(
            model_name='questionoption',
            index=models.Index(fields=['order'], name='question_op_order_651cbd_idx'),
        ),
        migrations.AddIndex(
            model_name='response',
            index=models.Index(fields=['question'], name='responses_questio_956ae8_idx'),
        ),
        migrations.AddIndex(
            model_name='response',
            index=models.Index(fields=['created_at'], name='responses_created_616bff_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='inspectionresponse',
            unique_together={('inspection', 'response')},
        ),
        migrations.AddIndex(
            model_name='section',
            index=models.Index(fields=['template'], name='sections_templat_61aeb5_idx'),
        ),
        migrations.AddIndex(
            model_name='section',
            index=models.Index(fields=['order'], name='sections_order_64336f_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['section'], name='questions_section_222a53_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['response_type'], name='questions_respons_90db80_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['order'], name='questions_order_2c3df8_idx'),
        ),
    ]
