# Generated by Django 5.1.6 on 2025-05-17 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_template_template_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='flagged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='logic_rules',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='multiple_selection',
            field=models.BooleanField(default=False),
        ),
    ]
