# Generated by Django 5.1.6 on 2025-04-21 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_inspection_inspectionresponse_mediaattachment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
    ]
