# Generated by Django 5.1.6 on 2025-05-18 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_question_flagged_question_logic_rules_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='annotation_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='response',
            name='media_attachments',
            field=models.ManyToManyField(blank=True, related_name='responses', to='users.mediaattachment'),
        ),
    ]
