# Generated by Django 5.1.6 on 2025-05-18 05:03

import django.contrib.postgres.fields
import django.db.models.deletion
import users.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_response_annotation_data_response_media_attachments'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_level', models.CharField(choices=[('owner', 'Owner'), ('editor', 'Editor'), ('viewer', 'Viewer')], default='viewer', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('pending', 'Pending'), ('expired', 'Expired')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_accessed', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Template Access',
                'verbose_name_plural': 'Template Access Permissions',
            },
        ),
        migrations.RemoveIndex(
            model_name='response',
            name='responses_questio_956ae8_idx',
        ),
        migrations.RemoveIndex(
            model_name='response',
            name='responses_created_616bff_idx',
        ),
        migrations.RemoveField(
            model_name='response',
            name='annotation_data',
        ),
        migrations.RemoveField(
            model_name='response',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='response',
            name='location_id',
        ),
        migrations.RemoveField(
            model_name='response',
            name='person_id',
        ),
        migrations.RemoveField(
            model_name='response',
            name='site_id',
        ),
        migrations.RemoveField(
            model_name='response',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='inspection',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('completed', 'Completed')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='mediaattachment',
            name='file',
            field=models.FileField(upload_to=users.models.MediaAttachment.upload_to),
        ),
        migrations.AlterField(
            model_name='section',
            name='colors',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='section',
            name='default_defects',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='section',
            name='sizes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), blank=True, default=list, size=None),
        ),
        migrations.AlterModelTable(
            name='response',
            table=None,
        ),
        migrations.AddField(
            model_name='templateaccess',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_permissions', to='users.template'),
        ),
        migrations.AddField(
            model_name='templateaccess',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_accesses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='templateaccess',
            index=models.Index(fields=['template', 'user'], name='users_templ_templat_ef8ce5_idx'),
        ),
        migrations.AddIndex(
            model_name='templateaccess',
            index=models.Index(fields=['user', 'permission_level'], name='users_templ_user_id_f99570_idx'),
        ),
        migrations.AddIndex(
            model_name='templateaccess',
            index=models.Index(fields=['template', 'permission_level'], name='users_templ_templat_497cbb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='templateaccess',
            unique_together={('template', 'user')},
        ),
    ]
