# Generated by Django 5.1.6 on 2025-05-18 06:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_templateaccess_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('codename', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Permission Type',
                'verbose_name_plural': 'Permission Types',
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_role',
            field=models.CharField(choices=[('admin', 'Admin'), ('inspector', 'Inspector'), ('regular', 'Regular User')], default='regular', max_length=20),
        ),
        migrations.AddField(
            model_name='templateaccess',
            name='granted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_permissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='templateaccess',
            name='permission_level',
            field=models.CharField(choices=[('owner', 'Owner'), ('admin', 'Administrator'), ('editor', 'Editor'), ('viewer', 'Viewer')], default='viewer', max_length=20),
        ),
        migrations.CreateModel(
            name='PermissionAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('grant', 'Permission Granted'), ('revoke', 'Permission Revoked'), ('modify', 'Permission Modified'), ('access', 'Resource Accessed')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('old_permission', models.CharField(blank=True, max_length=100, null=True)),
                ('new_permission', models.CharField(blank=True, max_length=100, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('additional_data', models.JSONField(blank=True, null=True)),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performed_permission_actions', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='permission_audit_logs', to='users.template')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Permission Audit Log',
                'verbose_name_plural': 'Permission Audit Logs',
                'indexes': [models.Index(fields=['user'], name='users_permi_user_id_63fe22_idx'), models.Index(fields=['template'], name='users_permi_templat_74bddb_idx'), models.Index(fields=['action'], name='users_permi_action_9cfbd0_idx'), models.Index(fields=['timestamp'], name='users_permi_timesta_04c6d9_idx')],
            },
        ),
        migrations.CreateModel(
            name='GranularPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_granular_permissions', to=settings.AUTH_USER_MODEL)),
                ('template_access', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='granular_permissions', to='users.templateaccess')),
                ('permission_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_permissions', to='users.permissiontype')),
            ],
            options={
                'verbose_name': 'Granular Permission',
                'verbose_name_plural': 'Granular Permissions',
                'unique_together': {('template_access', 'permission_type')},
            },
        ),
        migrations.CreateModel(
            name='TemplateAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('revoked', 'Revoked')], default='assigned', max_length=20)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('assigned_by', models.ForeignKey(limit_choices_to={'user_role': 'admin'}, on_delete=django.db.models.deletion.CASCADE, related_name='template_assignments', to=settings.AUTH_USER_MODEL)),
                ('inspector', models.ForeignKey(limit_choices_to={'user_role': 'inspector'}, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_templates', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='users.template')),
            ],
            options={
                'verbose_name': 'Template Assignment',
                'verbose_name_plural': 'Template Assignments',
                'db_table': 'template_assignments',
                'indexes': [models.Index(fields=['template'], name='template_as_templat_4bb4b5_idx'), models.Index(fields=['inspector'], name='template_as_inspect_6c1118_idx'), models.Index(fields=['status'], name='template_as_status_8902a3_idx'), models.Index(fields=['assigned_at'], name='template_as_assigne_feabb4_idx')],
                'unique_together': {('template', 'inspector')},
            },
        ),
    ]
