# Generated by Django 5.1.6 on 2025-05-18 08:42

from django.db import migrations


def update_users_to_admin(apps, schema_editor):
    """
    Update all existing users to have the 'admin' role.
    """
    CustomUser = apps.get_model('users', 'CustomUser')
    # Update all existing users to have the 'admin' role
    CustomUser.objects.all().update(user_role='admin')


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_permissiontype_customuser_user_role_and_more'),
    ]

    operations = [
        migrations.RunPython(update_users_to_admin, reverse_code=migrations.RunPython.noop),
    ]
