# Generated by Django 5.1.6 on 2025-05-19 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_update_existing_users_to_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='templateassignment',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='templateassignment',
            name='expired_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='templateassignment',
            name='status',
            field=models.CharField(choices=[('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('revoked', 'Revoked'), ('expired', 'Expired')], default='assigned', max_length=20),
        ),
    ]
