# Generated by Django 5.2.1 on 2025-06-10 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_templateassignment_due_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='garment_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
