version: '3.8'

services:
  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=Fash
      - POSTGRES_USER=log
      - POSTGRES_PASSWORD=log
    ports:
      - "5433:5432"  # Fixed port mapping
    restart: unless-stopped

  backend:
    build: .
    command: gunicorn FC.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DJANGO_SETTINGS_MODULE=FC.settings
      - DATABASE_HOST=db
      - DATABASE_NAME=Fash
      - DATABASE_USER=log
      - DATABASE_PASSWORD=log
      - CORS_ALLOW_ALL_ORIGINS=False
    restart: unless-stopped

  frontend:
    build: ./frontend
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/static
      - media_volume:/media
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  postgres_data:
  static_volume:
  media_volume:


